const words = [
    { id: 1, label: "Hacer", meaning: "Faire" },
    { id: 2, label: "Cebolla", meaning: "Oignon" },
    { id: 3, label: "Habitacion", meaning: "Chambre" },
    { id: 4, label: "Cena", meaning: "Diner" },
    { id: 5, label: "Desayuno", meaning: "Petit dejeuner" },
    { id: 6, label: "Nuevo", meaning: "Nouveau" },
    { id: 7, label: "Playa", meaning: "Plage" },
    { id: 8, label: "Montaña", meaning: "Montagne" },
    { id: 9, label: "Escuela", meaning: "École" },
    { id: 10, label: "Amigo", meaning: "Ami" },
    { id: 11, label: "Familia", meaning: "Famille" },
    { id: 12, label: "Comida", meaning: "Nourriture" },
    { id: 13, label: "Agua", meaning: "Eau" },
    { id: 14, label: "Cielo", meaning: "Ciel" },
    { id: 15, label: "Tierra", meaning: "Terre" },
    { id: 16, label: "Flor", meaning: "Fleur" },
    { id: 17, label: "Libro", meaning: "Livre" },
    { id: 18, label: "Canción", meaning: "Chanson" },
    { id: 19, label: "Arbol", meaning: "Arbre" },
    { id: 20, label: "Sol", meaning: "Soleil" },
    { id: 21, label: "Luna", meaning: "Lune" },
    { id: 22, label: "Estrella", meaning: "Étoile" },
    { id: 23, label: "Aire", meaning: "Air" },
    { id: 24, label: "Fuego", meaning: "Feu" },
    { id: 25, label: "Tiempo", meaning: "Temps" },
    { id: 26, label: "Mar", meaning: "Mer" },
    { id: 27, label: "Montaña", meaning: "Montagne" },
    { id: 28, label: "Río", meaning: "Rivière" },
    { id: 29, label: "Playa", meaning: "Plage" },
    { id: 30, label: "Viento", meaning: "Vent" },
    { id: 31, label: "Nieve", meaning: "Neige" },
    { id: 32, label: "Cielo", meaning: "Ciel" },
    { id: 33, label: "Tierra", meaning: "Terre" },
    { id: 34, label: "Flor", meaning: "Fleur" },
    { id: 35, label: "Libro", meaning: "Livre" },
    { id: 36, label: "Canción", meaning: "Chanson" },
    { id: 37, label: "Arbol", meaning: "Arbre" },
    { id: 38, label: "Sol", meaning: "Soleil" },
    { id: 39, label: "Luna", meaning: "Lune" },
    { id: 40, label: "Estrella", meaning: "Étoile" },
    { id: 41, label: "Aire", meaning: "Air" },
    { id: 42, label: "Fuego", meaning: "Feu" },
    { id: 43, label: "Tiempo", meaning: "Temps" },
    { id: 44, label: "Mar", meaning: "Mer" },
    { id: 45, label: "Montaña", meaning: "Montagne" },
    { id: 46, label: "Río", meaning: "Rivière" },
    { id: 47, label: "Playa", meaning: "Plage" },
    { id: 48, label: "Viento", meaning: "Vent" },
    { id: 49, label: "Nieve", meaning: "Neige" },
    { id: 50, label: "Viaje", meaning: "Voyage" },
  ];

export default words  